inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.6
  Exclude:
    - 'gemfiles/bin/*'
    - 'test/dummy/**/*'

Metrics/PerceivedComplexity:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'wicked_pdf.gemspec'

Metrics/ModuleLength:
  Exclude:
    # Excluding to keep the logic in one module for the time being.
    - 'lib/wicked_pdf/wicked_pdf_helper/assets.rb'

# I'd like wicked_pdf to keep Ruby 1.8 compatibility for now
Style/HashSyntax:
  EnforcedStyle: hash_rockets
